# Translate NAMCS2016's DIAG1 column from ICD10 to ICD9 codes

Note this fixes things in-place, and so should only be run once.

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import pandas as pd
from pandas.util.testing import assert_frame_equal
pd.set_option("display.max_columns",200)

In [2]:
tmp = pd.read_csv('NAMCS/namcs2016.csv', dtype=str)
translate = pd.read_csv('data_files/2016_I9gem2.csv', dtype='bytes', names=['ICD9','ICD10'])

This first part translates the diagnosis codes

In [3]:
tmp.DIAG1

0        7455
1        7454
2        4168
3        7454
4        4168
5        7455
6        7455
7        7455
8        7454
9        7470
10       4279
11       7470
12       7455
13       4279
14       7459
15       4279
16        NaN
17       4279
18       7455
19       4240
20       7455
21        NaN
22       7455
23       7470
24        NaN
25       7061
26       0780
27       3659
28       3659
29       3669
         ...
13135     NaN
13136     NaN
13137     NaN
13138    5531
13139    5531
13140     NaN
13141    7062
13142    5759
13143     NaN
13144     NaN
13145     NaN
13146     NaN
13147     NaN
13148    4556
13149     NaN
13150     NaN
13151    7944
13152     NaN
13153     NaN
13154     NaN
13155     NaN
13156     NaN
13157     NaN
13158    1539
13159     NaN
13160     NaN
13161     NaN
13162    1543
13163    1830
13164     NaN
Name: DIAG1, Length: 13165, dtype: object

In [9]:
tmp.DIAG5

0          -9
1          -9
2          -9
3          -9
4          -9
5          -9
6          -9
7          -9
8          -9
9          -9
10         -9
11         -9
12         -9
13         -9
14         -9
15         -9
16         -9
17         -9
18         -9
19         -9
20         -9
21         -9
22         -9
23         -9
24         -9
25         -9
26         -9
27       H21-
28         -9
29         -9
         ...
13135      -9
13136    K648
13137      -9
13138      -9
13139      -9
13140    N189
13141      -9
13142      -9
13143      -9
13144      -9
13145      -9
13146      -9
13147      -9
13148    M199
13149    D649
13150      -9
13151      -9
13152      -9
13153    C349
13154      -9
13155    T451
13156      -9
13157      -9
13158      -9
13159      -9
13160      -9
13161      -9
13162      -9
13163      -9
13164      -9
Name: DIAG5, Length: 13165, dtype: object

In [10]:
def g(x):
#     x = str(x, 'utf-8')
    if str(x) not in ['ZZZ0', 'ZZZ1', 'ZZZ2','ZZZ3','ZZZ4','ZZZ5','-9']:
        return x
    else:
        return np.nan

def f(x):
#     x = str(x, 'utf-8')
    if x in translate.ICD10.values:
        val = translate.loc[translate.ICD10 == x].ICD9
        return val.values[0]
    else:
        return np.nan

In [5]:
string = f"DIAG1"
tmp[string] =tmp[string].apply(g).apply(f)

In [12]:
strings = [f"DIAG2",f"DIAG3",f"DIAG4",f"DIAG5"]
for string in strings:
    tmp[string] =tmp[string].apply(g).apply(f)

In [13]:
tmp.DIAG2

0          NaN
1         4168
2         7470
3          NaN
4         7454
5         7459
6          NaN
7         7469
8          NaN
9         4179
10        7455
11        7454
12        4279
13        7454
14        4279
15        7454
16        7455
17        7470
18        4241
19        7454
20         NaN
21        7455
22         NaN
23        4279
24        V682
25         NaN
26         NaN
27        3669
28        3669
29         NaN
         ...
13135      NaN
13136    29632
13137     1539
13138    55321
13139      NaN
13140      NaN
13141      NaN
13142      NaN
13143      NaN
13144      NaN
13145      NaN
13146      NaN
13147      NaN
13148    53081
13149      NaN
13150      NaN
13151      NaN
13152      NaN
13153      NaN
13154      NaN
13155     V103
13156      NaN
13157      NaN
13158      NaN
13159    72982
13160      NaN
13161      NaN
13162    25000
13163      NaN
13164      NaN
Name: DIAG2, Length: 13165, dtype: object

In [14]:
# show the fields to keep
fields = pd.read_csv("data_files/keep_cols.csv", names=['titles'])
cols = [col for col in tmp.columns.tolist() if col in list(fields['titles'])]
tmp[cols]

,VMONTH,VDAYR,AGE,AGER,AGEDAYS,SEX,PREGNANT,GESTWK,ETHUN,RACEUN,ETHIM,PAYTYPER,RFV1,MAJOR,DIAG1,DIAG2,DIAG3,DIAG4,DIAG5,HTIN,WTLB,BMI,TEMPF,BPSYS,BPDIAS,GLUCOSE,BONEDENS,SUBSTED,MED1,MED2,MED3,HTWTFL,YEAR,PATWT
0,3,2,4,1,-7,1,-9,-9,1,-9,1,2,33500,3,7455,NaN,NaN,NaN,NaN,42,42,16.74,974,-9,-9,0,0,0,09545,14930,b'13118',0,2016,241154.17224
1,3,2,6,1,-7,1,-9,-9,1,-9,1,3,65000,3,7454,4168,NaN,NaN,NaN,43,48,18.25,976,-9,-9,0,0,0,09545,19210,b'14930',0,2016,241154.17224
2,3,2,3,1,-7,1,-9,-9,2,2,2,3,42050,5,4168,7470,NaN,NaN,NaN,38,32,15.58,978,-9,-9,1,0,0,09545,15600,b'29250',0,2016,241154.17224
3,3,2,3,1,-7,1,-9,-9,2,1,2,3,25200,2,7454,NaN,7852,NaN,NaN,38,36,17.53,978,-9,-9,1,0,0,09545,13118,b'11540',0,2016,241154.17224
4,3,2,5,1,-7,2,-7,-7,1,-9,1,3,14300,2,4168,7454,NaN,NaN,NaN,41,46,19.24,974,-9,-9,0,0,0,09545,19210,b'93313',0,2016,241154.17224
5,3,2,5,1,-7,1,-9,-9,2,2,2,3,10150,3,7455,7459,7454,NaN,NaN,40,35,15.38,978,-9,-9,1,0,0,09545,13118,b'-9',0,2016,241154.17224
6,3,2,5,1,-7,1,-9,-9,2,1,2,3,10150,2,7455,NaN,NaN,NaN,NaN,39,40,18.49,980,-9,-9,1,0,0,29250,14930,b'09545',0,2016,241154.17224
7,3,2,8,1,-7,1,-9,-9,1,-9,1,3,14051,2,7455,7469,NaN,NaN,NaN,49,56,16.4,980,-9,-9,1,0,0,09545,11540,b'93433',0,2016,241154.17224
8,3,2,6,1,-7,2,-7,-7,2,1,2,1,14150,2,7454,NaN,NaN,NaN,NaN,47,46,14.64,975,-9,-9,1,0,0,09545,29250,b'14930',0,2016,241154.17224
9,3,3,4,1,-7,1,-9,-9,1,-9,1,3,59300,2,7470,4179,7469,NaN,NaN,38,36,17.53,979,-9,-9,1,0,0,09545,19210,b'14930',0,2016,241154.17224
10,3,3,7,1,-7,1,-9,-9,2,3,2,3,59300,2,4279,7455,NaN,NaN,NaN,48,52,15.87,979,-9,-9,1,0,0,09545,11540,b'14930',0,2016,241154.17224
11,3,3,7,1,-7,1,-9,-9,2,3,2,3,14450,2,7470,7454,4279,NaN,NaN,51,60,16.22,978,-9,-9,1,0,0,15600,09545,b'29250',0,2016,241154.17224
12,3,3,6,1,-7,2,-7,-7,2,3,2,3,10150,2,7455,4279,NaN,NaN,NaN,46,50,16.61,981,-9,-9,0,0,0,09545,13118,b'14930',0,2016,241154.17224
13,3,3,10,1,-7,1,2,-9,2,3,2,3,10502,3,4279,7454,NaN,NaN,NaN,54,63,15.19,976,-9,-9,1,0,0,09545,13118,b'93433',0,2016,241154.17224
14,3,3,9,1,-7,1,2,-9,2,3,2,3,14200,2,7459,4279,NaN,NaN,NaN,54,59,14.22,979,-9,-9,1,0,0,09545,13118,b'29250',0,2016,241154.17224
15,3,5,9,1,-7,1,2,-9,2,3,2,3,29500,2,4279,7454,NaN,NaN,NaN,53,53,13.26,976,-9,-9,0,0,0,09545,10225,b'29250',0,2016,241154.17224
16,3,5,6,1,-7,2,-7,-7,1,-9,1,3,59300,2,NaN,7455,NaN,NaN,NaN,47,54,17.19,976,-9,-9,1,0,0,09545,11540,b'13118',0,2016,241154.17224
17,3,5,4,1,-7,2,-7,-7,2,2,2,3,42050,5,4279,7470,NaN,NaN,NaN,41,40,16.73,980,-9,-9,1,0,0,09545,19210,b'-9',0,2016,241154.17224
18,3,5,7,1,-7,1,-9,-9,1,-9,1,3,14450,3,7455,4241,NaN,NaN,NaN,49,54,15.81,978,-9,-9,1,0,0,09545,29250,b'14930',0,2016,241154.17224
19,3,6,7,1,-7,1,-9,-9,1,-9,1,3,59300,2,4240,7454,NaN,NaN,NaN,52,51,13.26,975,-9,-9,1,0,0,09545,19210,b'19218',0,2016,241154.17224
20,3,6,9,1,-7,2,-7,-7,2,3,2,3,14051,2,7455,NaN,4279,NaN,NaN,55,70,16.27,981,-9,-9,0,0,0,09545,29250,b'41800',0,2016,241154.17224
21,3,6,11,1,-7,1,2,-9,2,3,2,3,10150,2,NaN,7455,4279,NaN,NaN,57,109,23.58,977,-9,-9,1,0,0,09545,14930,b'13118',0,2016,241154.17224
22,3,6,8,1,-7,1,-9,-9,1,-9,1,3,26400,2,7455,NaN,4658,NaN,NaN,53,71,17.77,981,-9,-9,1,0,0,13118,14930,b'29250',0,2016,241154.17224
23,3,6,10,1,-7,1,2,-9,2,3,2,3,14200,3,7470,4279,NaN,NaN,NaN,53,55,13.76,975,-9,-9,1,0,0,09545,15600,b'29250',0,2016,241154.17224
24,2,3,32,3,-7,1,2,-9,2,-9,2,1,18300,2,NaN,V682,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,07289,-9,b'-9',0,2016,85471.53819
25,2,3,54,4,-7,1,2,-9,2,-9,2,1,18600,1,7061,NaN,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,09645,-9,b'-9',0,2016,85471.53819
26,2,3,10,1,-7,2,-7,-7,2,-9,2,1,20150,2,0780,NaN,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,10018,12222,b'-9',0,2016,85471.53819
27,10,2,74,5,-7,2,-7,-7,2,1,2,1,48000,2,3659,3669,25000,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,60550,-9,b'-9',0,2016,16256.51382
28,10,2,54,4,-7,2,-7,-7,2,1,2,1,24150,2,3659,3669,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,60550,-9,b'-9',0,2016,16256.51382
29,10,2,79,6,-7,1,-9,-9,-9,1,2,1,24100,2,3669,NaN,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,-9,-9,b'-9',0,2016,16256.51382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13135,1,4,78,6,-7,2,-7,-7,2,1,2,2,16150,5,NaN,NaN,1539,2469,NaN,71,126,17.57,955,100,60,0,0,0,17370,61245,b'-9',0,2016,33316.84584
13136,1,4,55,4,-7,2,-7,-7,2,1,2,2,26600,4,NaN,29632,4779,NaN,4550,72,178,24.14,980,124,82,0,0,0,25674,-9,b'-9',0,2016,33316.84584
13137,1,4,55,4,-7,1,2,-9,2,1,2,3,21000,5,NaN,1539,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,93396,-9,b'-9',0,2016,33316.84584
13138,1,6,58,4,-7,2,-7,-7,2,1,2,3,42000,4,5531,55321,27800,NaN,NaN,71,263,36.68,985,156,94,0,0,0,91062,06985,b'89020',0,2016,33316.84584
13139,1,6,75,6,-7,2,-7,-7,1,1,1,3,26600,5,5531,NaN,NaN,NaN,NaN,64,154,26.43,981,102,60,0,0,0,-9,-9,b'-9',0,2016,33316.84584
13140,1,6,81,6,-7,2,-7,-7,2,1,2,2,26600,5,NaN,NaN,49120,4439,5859,67,158,24.74,963,104,60,0,0,0,01030,02805,b'91063',0,2016,33316.84584
13141,1,6,66,5,-7,2,-7,-7,2,-9,2,2,19056,5,7062,NaN,27800,NaN,NaN,69,218,32.19,990,156,92,0,0,0,01030,91063,b'14930',0,2016,33316.84584
13142,1,6,59,4,-7,1,2,-9,2,1,2,3,46050,4,5759,NaN,NaN,NaN,NaN,65,156,25.96,980,116,80,0,0,0,-9,-9,b'-9',0,2016,33316.84584
13143,1,6,84,6,-7,1,-9,-9,2,1,2,2,13050,4,NaN,NaN,NaN,73300,NaN,66,118,19.04,969,130,60,0,0,0,91063,24890,b'-9',0,2016,33316.84584
13144,1,6,36,3,-7,2,-7,-7,2,-9,2,1,46050,4,NaN,NaN,27800,NaN,NaN,71,263,36.68,986,130,84,0,0,0,97020,92164,b'95050',0,2016,33316.84584
13145,1,6,27,3,-7,1,2,-9,1,1,1,1,16100,5,NaN,NaN,NaN,NaN,NaN,61,159,30.04,958,118,78,0,0,0,32930,-9,b'-9',0,2016,33316.84584
13146,1,6,70,5,-7,2,-7,-7,2,1,2,2,10600,5,NaN,NaN,29620,NaN,NaN,68,165,25.09,993,124,82,0,0,0,91063,06645,b'92164',0,2016,33316.84584
13147,1,6,55,4,-7,1,2,-9,1,1,1,3,42000,4,NaN,NaN,NaN,NaN,NaN,63,182,32.24,973,138,88,0,0,0,32930,-9,b'-9',0,2016,33316.84584
13148,1,6,71,5,-7,2,-7,-7,2,-9,2,2,25450,3,4556,53081,NaN,29620,NaN,69,220,32.48,984,126,82,0,0,0,17485,01034,b'03229',0,2016,33316.84584
13149,1,4,68,5,-7,1,-9,-9,2,1,2,2,48000,2,NaN,NaN,NaN,78702,2859,69,-9,-9,970,154,71,0,0,0,26255,98036,b'92141',0,2016,76524.39558
13150,1,4,70,5,-7,1,-9,-9,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,65,184,30.62,969,144,79,0,0,0,04423,00274,b'92160',0,2016,76524.39558
13151,1,4,80,6,-7,1,-9,-9,2,1,2,2,48000,2,7944,NaN,NaN,7049,NaN,63,143,25.33,966,140,82,0,0,0,07551,02875,b'10355',0,2016,76524.39558
13152,1,4,47,4,-7,1,2,-9,2,1,2,1,10150,2,NaN,NaN,NaN,NaN,NaN,64,177,30.38,982,119,69,0,0,0,99118,17370,b'61605',0,2016,76524.39558
13153,1,4,77,6,-7,2,-7,-7,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,68,172,26.15,972,115,56,0,0,0,12283,91096,b'93187',0,2016,76524.39558
13154,1,4,63,4,-7,2,-7,-7,-9,1,2,2,45210,2,NaN,NaN,NaN,NaN,NaN,76,255,31.04,954,142,73,0,0,0,02333,28495,b'32905',0,2016,76524.39558
13155,1,4,80,6,-7,1,-9,-9,2,1,2,2,15350,2,NaN,V103,NaN,28803,NaN,63,167,29.58,969,135,83,0,0,0,01640,92105,b'14985',0,2016,76524.39558
13156,1,4,66,5,-7,1,-9,-9,2,1,2,2,10150,2,NaN,NaN,NaN,NaN,NaN,68,172,26.15,969,125,67,0,0,0,04423,32735,b'34495',0,2016,76524.39558
13157,1,6,41,3,-7,1,2,-9,2,1,2,5,19351,2,NaN,NaN,NaN,NaN,NaN,65,251,41.76,978,143,80,0,0,0,04622,95181,b'02351',0,2016,76524.39558
13158,1,6,69,5,-7,2,-7,-7,2,1,2,2,48000,2,1539,NaN,NaN,1977,NaN,74,194,24.91,951,112,75,0,0,0,14985,92164,b'60790',0,2016,76524.39558
13159,1,6,58,4,-7,1,2,-9,1,5,1,5,48000,2,NaN,72982,NaN,NaN,NaN,61,176,33.25,985,138,78,0,0,0,02156,93181,b'91096',0,2016,76524.39558
13160,1,6,69,5,-7,2,-7,-7,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,69,155,22.89,964,131,64,0,0,0,08770,14083,b'96044',0,2016,76524.39558
13161,1,6,66,5,-7,2,-7,-7,2,1,2,2,10601,2,NaN,NaN,NaN,NaN,NaN,70,153,21.95,976,135,76,0,0,0,09600,92105,b'07470',0,2016,76524.39558
13162,1,6,80,6,-7,1,-9,-9,2,2,2,2,46050,3,1543,25000,NaN,NaN,NaN,66,147,23.72,979,110,64,0,0,0,93181,17485,b'12081',0,2016,76524.39558
13163,1,6,76,6,-7,1,-9,-9,1,1,1,2,12400,2,1830,NaN,3079,NaN,NaN,62,145,26.52,982,151,79,0,0,0,02900,08585,b'19242',0,2016,76524.39558
13164,1,6,73,5,-7,2,-7,-7,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,61,131,24.75,967,120,70,0,0,0,-9,-9,b'-9',0,2016,76524.39558

This part is to fix the medication columns

In [8]:
print(tmp[['MED1','MED2']])

           MED1      MED2
0      b'09545'  b'14930'
1      b'09545'  b'19210'
2      b'09545'  b'15600'
3      b'09545'  b'13118'
4      b'09545'  b'19210'
5      b'09545'  b'13118'
6      b'29250'  b'14930'
7      b'09545'  b'11540'
8      b'09545'  b'29250'
9      b'09545'  b'19210'
10     b'09545'  b'11540'
11     b'15600'  b'09545'
12     b'09545'  b'13118'
13     b'09545'  b'13118'
14     b'09545'  b'13118'
15     b'09545'  b'10225'
16     b'09545'  b'11540'
17     b'09545'  b'19210'
18     b'09545'  b'29250'
19     b'09545'  b'19210'
20     b'09545'  b'29250'
21     b'09545'  b'14930'
22     b'13118'  b'14930'
23     b'09545'  b'15600'
24     b'07289'     b'-9'
25     b'09645'     b'-9'
26     b'10018'  b'12222'
27     b'60550'     b'-9'
28     b'60550'     b'-9'
29        b'-9'     b'-9'
...         ...       ...
13135  b'17370'  b'61245'
13136  b'25674'     b'-9'
13137  b'93396'     b'-9'
13138  b'91062'  b'06985'
13139     b'-9'     b'-9'
13140  b'01030'  b'02805'
13141  b'01030'  b'91063'
13142     b'-9'     b'-9'
13143  b'91063'  b'24890'
13144  b'97020'  b'92164'
13145  b'32930'     b'-9'
13146  b'91063'  b'06645'
13147  b'32930'     b'-9'
13148  b'17485'  b'01034'
13149  b'26255'  b'98036'
13150  b'04423'  b'00274'
13151  b'07551'  b'02875'
13152  b'99118'  b'17370'
13153  b'12283'  b'91096'
13154  b'02333'  b'28495'
13155  b'01640'  b'92105'
13156  b'04423'  b'32735'
13157  b'04622'  b'95181'
13158  b'14985'  b'92164'
13159  b'02156'  b'93181'
13160  b'08770'  b'14083'
13161  b'09600'  b'92105'
13162  b'93181'  b'17485'
13163  b'02900'  b'08585'
13164     b'-9'     b'-9'

[13165 rows x 2 columns]

In [9]:
def h(x):
    return str(x)[2:-1]

for j in [1,2]:
    string = f"MED{j}"
    tmp[string] =tmp[string].apply(h)

In [15]:
def h(x):
    return str(x)[2:-1]

for j in [3]:
    string = f"MED{j}"
    tmp[string] =tmp[string].apply(h)

In [16]:
print(tmp[['MED1','MED2','MED3']])

        MED1   MED2   MED3
0      09545  14930  13118
1      09545  19210  14930
2      09545  15600  29250
3      09545  13118  11540
4      09545  19210  93313
5      09545  13118     -9
6      29250  14930  09545
7      09545  11540  93433
8      09545  29250  14930
9      09545  19210  14930
10     09545  11540  14930
11     15600  09545  29250
12     09545  13118  14930
13     09545  13118  93433
14     09545  13118  29250
15     09545  10225  29250
16     09545  11540  13118
17     09545  19210     -9
18     09545  29250  14930
19     09545  19210  19218
20     09545  29250  41800
21     09545  14930  13118
22     13118  14930  29250
23     09545  15600  29250
24     07289     -9     -9
25     09645     -9     -9
26     10018  12222     -9
27     60550     -9     -9
28     60550     -9     -9
29        -9     -9     -9
...      ...    ...    ...
13135  17370  61245     -9
13136  25674     -9     -9
13137  93396     -9     -9
13138  91062  06985  89020
13139     -9     -9     -9
13140  01030  02805  91063
13141  01030  91063  14930
13142     -9     -9     -9
13143  91063  24890     -9
13144  97020  92164  95050
13145  32930     -9     -9
13146  91063  06645  92164
13147  32930     -9     -9
13148  17485  01034  03229
13149  26255  98036  92141
13150  04423  00274  92160
13151  07551  02875  10355
13152  99118  17370  61605
13153  12283  91096  93187
13154  02333  28495  32905
13155  01640  92105  14985
13156  04423  32735  34495
13157  04622  95181  02351
13158  14985  92164  60790
13159  02156  93181  91096
13160  08770  14083  96044
13161  09600  92105  07470
13162  93181  17485  12081
13163  02900  08585  19242
13164     -9     -9     -9

[13165 rows x 3 columns]

In [17]:
tmp[cols]

,VMONTH,VDAYR,AGE,AGER,AGEDAYS,SEX,PREGNANT,GESTWK,ETHUN,RACEUN,ETHIM,PAYTYPER,RFV1,MAJOR,DIAG1,DIAG2,DIAG3,DIAG4,DIAG5,HTIN,WTLB,BMI,TEMPF,BPSYS,BPDIAS,GLUCOSE,BONEDENS,SUBSTED,MED1,MED2,MED3,HTWTFL,YEAR,PATWT
0,3,2,4,1,-7,1,-9,-9,1,-9,1,2,33500,3,7455,NaN,NaN,NaN,NaN,42,42,16.74,974,-9,-9,0,0,0,09545,14930,13118,0,2016,241154.17224
1,3,2,6,1,-7,1,-9,-9,1,-9,1,3,65000,3,7454,4168,NaN,NaN,NaN,43,48,18.25,976,-9,-9,0,0,0,09545,19210,14930,0,2016,241154.17224
2,3,2,3,1,-7,1,-9,-9,2,2,2,3,42050,5,4168,7470,NaN,NaN,NaN,38,32,15.58,978,-9,-9,1,0,0,09545,15600,29250,0,2016,241154.17224
3,3,2,3,1,-7,1,-9,-9,2,1,2,3,25200,2,7454,NaN,7852,NaN,NaN,38,36,17.53,978,-9,-9,1,0,0,09545,13118,11540,0,2016,241154.17224
4,3,2,5,1,-7,2,-7,-7,1,-9,1,3,14300,2,4168,7454,NaN,NaN,NaN,41,46,19.24,974,-9,-9,0,0,0,09545,19210,93313,0,2016,241154.17224
5,3,2,5,1,-7,1,-9,-9,2,2,2,3,10150,3,7455,7459,7454,NaN,NaN,40,35,15.38,978,-9,-9,1,0,0,09545,13118,-9,0,2016,241154.17224
6,3,2,5,1,-7,1,-9,-9,2,1,2,3,10150,2,7455,NaN,NaN,NaN,NaN,39,40,18.49,980,-9,-9,1,0,0,29250,14930,09545,0,2016,241154.17224
7,3,2,8,1,-7,1,-9,-9,1,-9,1,3,14051,2,7455,7469,NaN,NaN,NaN,49,56,16.4,980,-9,-9,1,0,0,09545,11540,93433,0,2016,241154.17224
8,3,2,6,1,-7,2,-7,-7,2,1,2,1,14150,2,7454,NaN,NaN,NaN,NaN,47,46,14.64,975,-9,-9,1,0,0,09545,29250,14930,0,2016,241154.17224
9,3,3,4,1,-7,1,-9,-9,1,-9,1,3,59300,2,7470,4179,7469,NaN,NaN,38,36,17.53,979,-9,-9,1,0,0,09545,19210,14930,0,2016,241154.17224
10,3,3,7,1,-7,1,-9,-9,2,3,2,3,59300,2,4279,7455,NaN,NaN,NaN,48,52,15.87,979,-9,-9,1,0,0,09545,11540,14930,0,2016,241154.17224
11,3,3,7,1,-7,1,-9,-9,2,3,2,3,14450,2,7470,7454,4279,NaN,NaN,51,60,16.22,978,-9,-9,1,0,0,15600,09545,29250,0,2016,241154.17224
12,3,3,6,1,-7,2,-7,-7,2,3,2,3,10150,2,7455,4279,NaN,NaN,NaN,46,50,16.61,981,-9,-9,0,0,0,09545,13118,14930,0,2016,241154.17224
13,3,3,10,1,-7,1,2,-9,2,3,2,3,10502,3,4279,7454,NaN,NaN,NaN,54,63,15.19,976,-9,-9,1,0,0,09545,13118,93433,0,2016,241154.17224
14,3,3,9,1,-7,1,2,-9,2,3,2,3,14200,2,7459,4279,NaN,NaN,NaN,54,59,14.22,979,-9,-9,1,0,0,09545,13118,29250,0,2016,241154.17224
15,3,5,9,1,-7,1,2,-9,2,3,2,3,29500,2,4279,7454,NaN,NaN,NaN,53,53,13.26,976,-9,-9,0,0,0,09545,10225,29250,0,2016,241154.17224
16,3,5,6,1,-7,2,-7,-7,1,-9,1,3,59300,2,NaN,7455,NaN,NaN,NaN,47,54,17.19,976,-9,-9,1,0,0,09545,11540,13118,0,2016,241154.17224
17,3,5,4,1,-7,2,-7,-7,2,2,2,3,42050,5,4279,7470,NaN,NaN,NaN,41,40,16.73,980,-9,-9,1,0,0,09545,19210,-9,0,2016,241154.17224
18,3,5,7,1,-7,1,-9,-9,1,-9,1,3,14450,3,7455,4241,NaN,NaN,NaN,49,54,15.81,978,-9,-9,1,0,0,09545,29250,14930,0,2016,241154.17224
19,3,6,7,1,-7,1,-9,-9,1,-9,1,3,59300,2,4240,7454,NaN,NaN,NaN,52,51,13.26,975,-9,-9,1,0,0,09545,19210,19218,0,2016,241154.17224
20,3,6,9,1,-7,2,-7,-7,2,3,2,3,14051,2,7455,NaN,4279,NaN,NaN,55,70,16.27,981,-9,-9,0,0,0,09545,29250,41800,0,2016,241154.17224
21,3,6,11,1,-7,1,2,-9,2,3,2,3,10150,2,NaN,7455,4279,NaN,NaN,57,109,23.58,977,-9,-9,1,0,0,09545,14930,13118,0,2016,241154.17224
22,3,6,8,1,-7,1,-9,-9,1,-9,1,3,26400,2,7455,NaN,4658,NaN,NaN,53,71,17.77,981,-9,-9,1,0,0,13118,14930,29250,0,2016,241154.17224
23,3,6,10,1,-7,1,2,-9,2,3,2,3,14200,3,7470,4279,NaN,NaN,NaN,53,55,13.76,975,-9,-9,1,0,0,09545,15600,29250,0,2016,241154.17224
24,2,3,32,3,-7,1,2,-9,2,-9,2,1,18300,2,NaN,V682,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,07289,-9,-9,0,2016,85471.53819
25,2,3,54,4,-7,1,2,-9,2,-9,2,1,18600,1,7061,NaN,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,09645,-9,-9,0,2016,85471.53819
26,2,3,10,1,-7,2,-7,-7,2,-9,2,1,20150,2,0780,NaN,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,10018,12222,-9,0,2016,85471.53819
27,10,2,74,5,-7,2,-7,-7,2,1,2,1,48000,2,3659,3669,25000,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,60550,-9,-9,0,2016,16256.51382
28,10,2,54,4,-7,2,-7,-7,2,1,2,1,24150,2,3659,3669,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,60550,-9,-9,0,2016,16256.51382
29,10,2,79,6,-7,1,-9,-9,-9,1,2,1,24100,2,3669,NaN,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,-9,-9,-9,0,2016,16256.51382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13135,1,4,78,6,-7,2,-7,-7,2,1,2,2,16150,5,NaN,NaN,1539,2469,NaN,71,126,17.57,955,100,60,0,0,0,17370,61245,-9,0,2016,33316.84584
13136,1,4,55,4,-7,2,-7,-7,2,1,2,2,26600,4,NaN,29632,4779,NaN,4550,72,178,24.14,980,124,82,0,0,0,25674,-9,-9,0,2016,33316.84584
13137,1,4,55,4,-7,1,2,-9,2,1,2,3,21000,5,NaN,1539,NaN,NaN,NaN,-9,-9,-9,-9,-9,-9,0,0,0,93396,-9,-9,0,2016,33316.84584
13138,1,6,58,4,-7,2,-7,-7,2,1,2,3,42000,4,5531,55321,27800,NaN,NaN,71,263,36.68,985,156,94,0,0,0,91062,06985,89020,0,2016,33316.84584
13139,1,6,75,6,-7,2,-7,-7,1,1,1,3,26600,5,5531,NaN,NaN,NaN,NaN,64,154,26.43,981,102,60,0,0,0,-9,-9,-9,0,2016,33316.84584
13140,1,6,81,6,-7,2,-7,-7,2,1,2,2,26600,5,NaN,NaN,49120,4439,5859,67,158,24.74,963,104,60,0,0,0,01030,02805,91063,0,2016,33316.84584
13141,1,6,66,5,-7,2,-7,-7,2,-9,2,2,19056,5,7062,NaN,27800,NaN,NaN,69,218,32.19,990,156,92,0,0,0,01030,91063,14930,0,2016,33316.84584
13142,1,6,59,4,-7,1,2,-9,2,1,2,3,46050,4,5759,NaN,NaN,NaN,NaN,65,156,25.96,980,116,80,0,0,0,-9,-9,-9,0,2016,33316.84584
13143,1,6,84,6,-7,1,-9,-9,2,1,2,2,13050,4,NaN,NaN,NaN,73300,NaN,66,118,19.04,969,130,60,0,0,0,91063,24890,-9,0,2016,33316.84584
13144,1,6,36,3,-7,2,-7,-7,2,-9,2,1,46050,4,NaN,NaN,27800,NaN,NaN,71,263,36.68,986,130,84,0,0,0,97020,92164,95050,0,2016,33316.84584
13145,1,6,27,3,-7,1,2,-9,1,1,1,1,16100,5,NaN,NaN,NaN,NaN,NaN,61,159,30.04,958,118,78,0,0,0,32930,-9,-9,0,2016,33316.84584
13146,1,6,70,5,-7,2,-7,-7,2,1,2,2,10600,5,NaN,NaN,29620,NaN,NaN,68,165,25.09,993,124,82,0,0,0,91063,06645,92164,0,2016,33316.84584
13147,1,6,55,4,-7,1,2,-9,1,1,1,3,42000,4,NaN,NaN,NaN,NaN,NaN,63,182,32.24,973,138,88,0,0,0,32930,-9,-9,0,2016,33316.84584
13148,1,6,71,5,-7,2,-7,-7,2,-9,2,2,25450,3,4556,53081,NaN,29620,NaN,69,220,32.48,984,126,82,0,0,0,17485,01034,03229,0,2016,33316.84584
13149,1,4,68,5,-7,1,-9,-9,2,1,2,2,48000,2,NaN,NaN,NaN,78702,2859,69,-9,-9,970,154,71,0,0,0,26255,98036,92141,0,2016,76524.39558
13150,1,4,70,5,-7,1,-9,-9,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,65,184,30.62,969,144,79,0,0,0,04423,00274,92160,0,2016,76524.39558
13151,1,4,80,6,-7,1,-9,-9,2,1,2,2,48000,2,7944,NaN,NaN,7049,NaN,63,143,25.33,966,140,82,0,0,0,07551,02875,10355,0,2016,76524.39558
13152,1,4,47,4,-7,1,2,-9,2,1,2,1,10150,2,NaN,NaN,NaN,NaN,NaN,64,177,30.38,982,119,69,0,0,0,99118,17370,61605,0,2016,76524.39558
13153,1,4,77,6,-7,2,-7,-7,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,68,172,26.15,972,115,56,0,0,0,12283,91096,93187,0,2016,76524.39558
13154,1,4,63,4,-7,2,-7,-7,-9,1,2,2,45210,2,NaN,NaN,NaN,NaN,NaN,76,255,31.04,954,142,73,0,0,0,02333,28495,32905,0,2016,76524.39558
13155,1,4,80,6,-7,1,-9,-9,2,1,2,2,15350,2,NaN,V103,NaN,28803,NaN,63,167,29.58,969,135,83,0,0,0,01640,92105,14985,0,2016,76524.39558
13156,1,4,66,5,-7,1,-9,-9,2,1,2,2,10150,2,NaN,NaN,NaN,NaN,NaN,68,172,26.15,969,125,67,0,0,0,04423,32735,34495,0,2016,76524.39558
13157,1,6,41,3,-7,1,2,-9,2,1,2,5,19351,2,NaN,NaN,NaN,NaN,NaN,65,251,41.76,978,143,80,0,0,0,04622,95181,02351,0,2016,76524.39558
13158,1,6,69,5,-7,2,-7,-7,2,1,2,2,48000,2,1539,NaN,NaN,1977,NaN,74,194,24.91,951,112,75,0,0,0,14985,92164,60790,0,2016,76524.39558
13159,1,6,58,4,-7,1,2,-9,1,5,1,5,48000,2,NaN,72982,NaN,NaN,NaN,61,176,33.25,985,138,78,0,0,0,02156,93181,91096,0,2016,76524.39558
13160,1,6,69,5,-7,2,-7,-7,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,69,155,22.89,964,131,64,0,0,0,08770,14083,96044,0,2016,76524.39558
13161,1,6,66,5,-7,2,-7,-7,2,1,2,2,10601,2,NaN,NaN,NaN,NaN,NaN,70,153,21.95,976,135,76,0,0,0,09600,92105,07470,0,2016,76524.39558
13162,1,6,80,6,-7,1,-9,-9,2,2,2,2,46050,3,1543,25000,NaN,NaN,NaN,66,147,23.72,979,110,64,0,0,0,93181,17485,12081,0,2016,76524.39558
13163,1,6,76,6,-7,1,-9,-9,1,1,1,2,12400,2,1830,NaN,3079,NaN,NaN,62,145,26.52,982,151,79,0,0,0,02900,08585,19242,0,2016,76524.39558
13164,1,6,73,5,-7,2,-7,-7,2,1,2,2,48000,2,NaN,NaN,NaN,NaN,NaN,61,131,24.75,967,120,70,0,0,0,-9,-9,-9,0,2016,76524.39558

fix other values to be ints, not floats, where appropriate

In [24]:
def k(x):
    if str(x)[-2:]=='.0':
        return str(x)[:-2]
    else:
        return str(x)

for j in tmp.columns.tolist():
    tmp[j] =tmp[j].apply(k)

In [25]:
tmp[cols]

,VMONTH,VDAYR,AGE,AGER,AGEDAYS,SEX,PREGNANT,GESTWK,ETHUN,RACEUN,ETHIM,PAYTYPER,RFV1,MAJOR,DIAG1,DIAG2,DIAG3,DIAG4,DIAG5,HTIN,WTLB,BMI,TEMPF,BPSYS,BPDIAS,GLUCOSE,BONEDENS,SUBSTED,MED1,MED2,MED3,HTWTFL,YEAR,PATWT
0,3,2,4,1,-7,1,-9,-9,1,-9,1,2,33500,3,7455,nan,nan,nan,nan,42,42,16.74,974,-9,-9,0,0,0,09545,14930,13118,0,2016,241154.17224
1,3,2,6,1,-7,1,-9,-9,1,-9,1,3,65000,3,7454,4168,nan,nan,nan,43,48,18.25,976,-9,-9,0,0,0,09545,19210,14930,0,2016,241154.17224
2,3,2,3,1,-7,1,-9,-9,2,2,2,3,42050,5,4168,7470,nan,nan,nan,38,32,15.58,978,-9,-9,1,0,0,09545,15600,29250,0,2016,241154.17224
3,3,2,3,1,-7,1,-9,-9,2,1,2,3,25200,2,7454,nan,7852,nan,nan,38,36,17.53,978,-9,-9,1,0,0,09545,13118,11540,0,2016,241154.17224
4,3,2,5,1,-7,2,-7,-7,1,-9,1,3,14300,2,4168,7454,nan,nan,nan,41,46,19.24,974,-9,-9,0,0,0,09545,19210,93313,0,2016,241154.17224
5,3,2,5,1,-7,1,-9,-9,2,2,2,3,10150,3,7455,7459,7454,nan,nan,40,35,15.38,978,-9,-9,1,0,0,09545,13118,-9,0,2016,241154.17224
6,3,2,5,1,-7,1,-9,-9,2,1,2,3,10150,2,7455,nan,nan,nan,nan,39,40,18.49,980,-9,-9,1,0,0,29250,14930,09545,0,2016,241154.17224
7,3,2,8,1,-7,1,-9,-9,1,-9,1,3,14051,2,7455,7469,nan,nan,nan,49,56,16.4,980,-9,-9,1,0,0,09545,11540,93433,0,2016,241154.17224
8,3,2,6,1,-7,2,-7,-7,2,1,2,1,14150,2,7454,nan,nan,nan,nan,47,46,14.64,975,-9,-9,1,0,0,09545,29250,14930,0,2016,241154.17224
9,3,3,4,1,-7,1,-9,-9,1,-9,1,3,59300,2,7470,4179,7469,nan,nan,38,36,17.53,979,-9,-9,1,0,0,09545,19210,14930,0,2016,241154.17224
10,3,3,7,1,-7,1,-9,-9,2,3,2,3,59300,2,4279,7455,nan,nan,nan,48,52,15.87,979,-9,-9,1,0,0,09545,11540,14930,0,2016,241154.17224
11,3,3,7,1,-7,1,-9,-9,2,3,2,3,14450,2,7470,7454,4279,nan,nan,51,60,16.22,978,-9,-9,1,0,0,15600,09545,29250,0,2016,241154.17224
12,3,3,6,1,-7,2,-7,-7,2,3,2,3,10150,2,7455,4279,nan,nan,nan,46,50,16.61,981,-9,-9,0,0,0,09545,13118,14930,0,2016,241154.17224
13,3,3,10,1,-7,1,2,-9,2,3,2,3,10502,3,4279,7454,nan,nan,nan,54,63,15.19,976,-9,-9,1,0,0,09545,13118,93433,0,2016,241154.17224
14,3,3,9,1,-7,1,2,-9,2,3,2,3,14200,2,7459,4279,nan,nan,nan,54,59,14.22,979,-9,-9,1,0,0,09545,13118,29250,0,2016,241154.17224
15,3,5,9,1,-7,1,2,-9,2,3,2,3,29500,2,4279,7454,nan,nan,nan,53,53,13.26,976,-9,-9,0,0,0,09545,10225,29250,0,2016,241154.17224
16,3,5,6,1,-7,2,-7,-7,1,-9,1,3,59300,2,nan,7455,nan,nan,nan,47,54,17.19,976,-9,-9,1,0,0,09545,11540,13118,0,2016,241154.17224
17,3,5,4,1,-7,2,-7,-7,2,2,2,3,42050,5,4279,7470,nan,nan,nan,41,40,16.73,980,-9,-9,1,0,0,09545,19210,-9,0,2016,241154.17224
18,3,5,7,1,-7,1,-9,-9,1,-9,1,3,14450,3,7455,4241,nan,nan,nan,49,54,15.81,978,-9,-9,1,0,0,09545,29250,14930,0,2016,241154.17224
19,3,6,7,1,-7,1,-9,-9,1,-9,1,3,59300,2,4240,7454,nan,nan,nan,52,51,13.26,975,-9,-9,1,0,0,09545,19210,19218,0,2016,241154.17224
20,3,6,9,1,-7,2,-7,-7,2,3,2,3,14051,2,7455,nan,4279,nan,nan,55,70,16.27,981,-9,-9,0,0,0,09545,29250,41800,0,2016,241154.17224
21,3,6,11,1,-7,1,2,-9,2,3,2,3,10150,2,nan,7455,4279,nan,nan,57,109,23.58,977,-9,-9,1,0,0,09545,14930,13118,0,2016,241154.17224
22,3,6,8,1,-7,1,-9,-9,1,-9,1,3,26400,2,7455,nan,4658,nan,nan,53,71,17.77,981,-9,-9,1,0,0,13118,14930,29250,0,2016,241154.17224
23,3,6,10,1,-7,1,2,-9,2,3,2,3,14200,3,7470,4279,nan,nan,nan,53,55,13.76,975,-9,-9,1,0,0,09545,15600,29250,0,2016,241154.17224
24,2,3,32,3,-7,1,2,-9,2,-9,2,1,18300,2,nan,V682,nan,nan,nan,-9,-9,-9,-9,-9,-9,0,0,0,07289,-9,-9,0,2016,85471.53819
25,2,3,54,4,-7,1,2,-9,2,-9,2,1,18600,1,7061,nan,nan,nan,nan,-9,-9,-9,-9,-9,-9,0,0,0,09645,-9,-9,0,2016,85471.53819
26,2,3,10,1,-7,2,-7,-7,2,-9,2,1,20150,2,0780,nan,nan,nan,nan,-9,-9,-9,-9,-9,-9,0,0,0,10018,12222,-9,0,2016,85471.53819
27,10,2,74,5,-7,2,-7,-7,2,1,2,1,48000,2,3659,3669,25000,nan,nan,-9,-9,-9,-9,-9,-9,0,0,0,60550,-9,-9,0,2016,16256.51382
28,10,2,54,4,-7,2,-7,-7,2,1,2,1,24150,2,3659,3669,nan,nan,nan,-9,-9,-9,-9,-9,-9,0,0,0,60550,-9,-9,0,2016,16256.51382
29,10,2,79,6,-7,1,-9,-9,-9,1,2,1,24100,2,3669,nan,nan,nan,nan,-9,-9,-9,-9,-9,-9,0,0,0,-9,-9,-9,0,2016,16256.51382
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13135,1,4,78,6,-7,2,-7,-7,2,1,2,2,16150,5,nan,nan,1539,2469,nan,71,126,17.57,955,100,60,0,0,0,17370,61245,-9,0,2016,33316.84584
13136,1,4,55,4,-7,2,-7,-7,2,1,2,2,26600,4,nan,29632,4779,nan,4550,72,178,24.14,980,124,82,0,0,0,25674,-9,-9,0,2016,33316.84584
13137,1,4,55,4,-7,1,2,-9,2,1,2,3,21000,5,nan,1539,nan,nan,nan,-9,-9,-9,-9,-9,-9,0,0,0,93396,-9,-9,0,2016,33316.84584
13138,1,6,58,4,-7,2,-7,-7,2,1,2,3,42000,4,5531,55321,27800,nan,nan,71,263,36.68,985,156,94,0,0,0,91062,06985,89020,0,2016,33316.84584
13139,1,6,75,6,-7,2,-7,-7,1,1,1,3,26600,5,5531,nan,nan,nan,nan,64,154,26.43,981,102,60,0,0,0,-9,-9,-9,0,2016,33316.84584
13140,1,6,81,6,-7,2,-7,-7,2,1,2,2,26600,5,nan,nan,49120,4439,5859,67,158,24.74,963,104,60,0,0,0,01030,02805,91063,0,2016,33316.84584
13141,1,6,66,5,-7,2,-7,-7,2,-9,2,2,19056,5,7062,nan,27800,nan,nan,69,218,32.19,990,156,92,0,0,0,01030,91063,14930,0,2016,33316.84584
13142,1,6,59,4,-7,1,2,-9,2,1,2,3,46050,4,5759,nan,nan,nan,nan,65,156,25.96,980,116,80,0,0,0,-9,-9,-9,0,2016,33316.84584
13143,1,6,84,6,-7,1,-9,-9,2,1,2,2,13050,4,nan,nan,nan,73300,nan,66,118,19.04,969,130,60,0,0,0,91063,24890,-9,0,2016,33316.84584
13144,1,6,36,3,-7,2,-7,-7,2,-9,2,1,46050,4,nan,nan,27800,nan,nan,71,263,36.68,986,130,84,0,0,0,97020,92164,95050,0,2016,33316.84584
13145,1,6,27,3,-7,1,2,-9,1,1,1,1,16100,5,nan,nan,nan,nan,nan,61,159,30.04,958,118,78,0,0,0,32930,-9,-9,0,2016,33316.84584
13146,1,6,70,5,-7,2,-7,-7,2,1,2,2,10600,5,nan,nan,29620,nan,nan,68,165,25.09,993,124,82,0,0,0,91063,06645,92164,0,2016,33316.84584
13147,1,6,55,4,-7,1,2,-9,1,1,1,3,42000,4,nan,nan,nan,nan,nan,63,182,32.24,973,138,88,0,0,0,32930,-9,-9,0,2016,33316.84584
13148,1,6,71,5,-7,2,-7,-7,2,-9,2,2,25450,3,4556,53081,nan,29620,nan,69,220,32.48,984,126,82,0,0,0,17485,01034,03229,0,2016,33316.84584
13149,1,4,68,5,-7,1,-9,-9,2,1,2,2,48000,2,nan,nan,nan,78702,2859,69,-9,-9,970,154,71,0,0,0,26255,98036,92141,0,2016,76524.39558
13150,1,4,70,5,-7,1,-9,-9,2,1,2,2,48000,2,nan,nan,nan,nan,nan,65,184,30.62,969,144,79,0,0,0,04423,00274,92160,0,2016,76524.39558
13151,1,4,80,6,-7,1,-9,-9,2,1,2,2,48000,2,7944,nan,nan,7049,nan,63,143,25.33,966,140,82,0,0,0,07551,02875,10355,0,2016,76524.39558
13152,1,4,47,4,-7,1,2,-9,2,1,2,1,10150,2,nan,nan,nan,nan,nan,64,177,30.38,982,119,69,0,0,0,99118,17370,61605,0,2016,76524.39558
13153,1,4,77,6,-7,2,-7,-7,2,1,2,2,48000,2,nan,nan,nan,nan,nan,68,172,26.15,972,115,56,0,0,0,12283,91096,93187,0,2016,76524.39558
13154,1,4,63,4,-7,2,-7,-7,-9,1,2,2,45210,2,nan,nan,nan,nan,nan,76,255,31.04,954,142,73,0,0,0,02333,28495,32905,0,2016,76524.39558
13155,1,4,80,6,-7,1,-9,-9,2,1,2,2,15350,2,nan,V103,nan,28803,nan,63,167,29.58,969,135,83,0,0,0,01640,92105,14985,0,2016,76524.39558
13156,1,4,66,5,-7,1,-9,-9,2,1,2,2,10150,2,nan,nan,nan,nan,nan,68,172,26.15,969,125,67,0,0,0,04423,32735,34495,0,2016,76524.39558
13157,1,6,41,3,-7,1,2,-9,2,1,2,5,19351,2,nan,nan,nan,nan,nan,65,251,41.76,978,143,80,0,0,0,04622,95181,02351,0,2016,76524.39558
13158,1,6,69,5,-7,2,-7,-7,2,1,2,2,48000,2,1539,nan,nan,1977,nan,74,194,24.91,951,112,75,0,0,0,14985,92164,60790,0,2016,76524.39558
13159,1,6,58,4,-7,1,2,-9,1,5,1,5,48000,2,nan,72982,nan,nan,nan,61,176,33.25,985,138,78,0,0,0,02156,93181,91096,0,2016,76524.39558
13160,1,6,69,5,-7,2,-7,-7,2,1,2,2,48000,2,nan,nan,nan,nan,nan,69,155,22.89,964,131,64,0,0,0,08770,14083,96044,0,2016,76524.39558
13161,1,6,66,5,-7,2,-7,-7,2,1,2,2,10601,2,nan,nan,nan,nan,nan,70,153,21.95,976,135,76,0,0,0,09600,92105,07470,0,2016,76524.39558
13162,1,6,80,6,-7,1,-9,-9,2,2,2,2,46050,3,1543,25000,nan,nan,nan,66,147,23.72,979,110,64,0,0,0,93181,17485,12081,0,2016,76524.39558
13163,1,6,76,6,-7,1,-9,-9,1,1,1,2,12400,2,1830,nan,3079,nan,nan,62,145,26.52,982,151,79,0,0,0,02900,08585,19242,0,2016,76524.39558
13164,1,6,73,5,-7,2,-7,-7,2,1,2,2,48000,2,nan,nan,nan,nan,nan,61,131,24.75,967,120,70,0,0,0,-9,-9,-9,0,2016,76524.39558

In [26]:
tmp.to_csv('NAMCS/namcs2016.csv')