# Process NAMCS files for use

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import pandas as pd
from pandas.util.testing import assert_frame_equal
pd.set_option("display.max_columns",200)

In [2]:
# Pain 'diagnoses' according to the ICD-9-CM documentation followed by NAMCS
# Note that, as per NAMCS documentation guidelines, 
# any codes that don't have 2 decimal places have a '-' at the end
# There's an implied two-point decimal in each of these numbers
# from https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/codes.html

icd9 = pd.read_csv("data_files/icd9.csv")

In [3]:
# Drugs come from NCHS drug codes
# These can be found at https://www2.cdc.gov/drugs/applicationnav1.asp

# To strip whitespace from end of lines:
# find . -name "*.csv"  | xargs sed -i 's/[ \t]*$//'

drugs = pd.read_csv("data_files/drugs.csv", sep=',', dtype = {'drug':str,'code':str})

In [4]:
drugs.columns.tolist()

['drug', 'code', 'ingredient']

In [5]:
#append a '-' to 4-digit and '--' to 3-digit codes to make sure that all
# are in the NAMCS standard format
f = lambda x:  x + '-' if len(x) == 4 else x #check 4-digit nums
g = lambda x:  x + '--' if len(x) == 3 else x #check 3-digit nums

icd9["DIAGNOSIS CODE"] = icd9["DIAGNOSIS CODE"].map(f).map(g)

In [6]:
# This cell translates NAMCS2016's diagnosis column from ICD10 to ICD9 codes

In [7]:
# These are the fields to keep
fields = pd.read_csv("data_files/keep_cols.csv", names=['titles'])

In [8]:
# Thesse functions are for processing of data in certain years, as described in the cell below
def g(x):
    '''900000 means 'blank' in '93 and '94. In '94, 209900 and 209970 mean blank as well'''
    if str(x) not in ['900000', '209900', '209970', 'V9900','V9910','V9920','00000','V990-','V991-','V992-','V993-','V997-']:
        return x
    else:
        return np.nan 
def h(x):
    '''
    Only for '93 and '94
    if 1st digit is 1, remove it, if it starts with 2, then take away the 20 and put a 'V' in'''
    if len(str(x)) == 6:
        if str(x)[0] == '1':
            return str(x)[1:]
        else:
            return 'V' + str(x)[2:]

In [9]:
# This loop adds all tables into a list, and drops all of the fields we don't care about as it goes
# This allows us to have a much smaller sized dataset to work with
year = []
# ACHTUNG!! Make sure you only add 2016 AFTER using the 2016 script to translate diagnoses to ICD-9 codes!
for i in range(1993,2017):
    tmp = pd.read_csv(f"NAMCS/namcs{str(i)}.csv",dtype=str)
    tmp.columns = tmp.columns.str.upper() # Make all column labels upper case
    cols = [col for col in tmp.columns.tolist() if col in list(fields['titles'])]
    tmp = tmp[cols]
    tmp = tmp.rename(index=str, columns={"ETHUN": "ETHNIC","ETHNICFL":"ETHNIC", "RACEUN": "RACE","PAYTYPER":"PAYTYPE","REGIONOFF":"REGION"}) #Make sure that we stack the correct columns on top of each other
    
    if i == 1993 or i == 1994:
        string = "DIAG1"
        tmp[string] =tmp[string].apply(g)
        tmp[string] =tmp[string].apply(h)

    year.append(tmp)
result = pd.concat(year, axis=0, join='outer', ignore_index=False, sort=False)

In [10]:
# In this cell we determine to keep the ETHUN column only if the ETHNIC column is null or nan
result['ETHNIC'] = result.apply(
    lambda row: row['ETHUN'] if pd.isna(row['ETHNIC']) else row['ETHNIC'],
    axis=1
)

In [14]:
# Add a columns called 'received' that is a 1 if the patient received an opiate, and 0 otherwise
# Note there are two medications allowed to every patient, but not 30

def opiate(df):
    if df['MED1'] in list(drugs['code']) or df['MED2'] in list(drugs['code']) or df['MED3'] in list(drugs['code']):
        return 1
    else:
        return 0

result['received'] = result.apply(opiate,axis=1)

In [15]:
# Replace all values that mean NaN with Nan
result  = result.replace({-9.0:np.nan,'-9.0':np.nan,-9:np.nan,'-9':np.nan,-7:np.nan,'-7':np.nan,-7.0:np.nan,'-7.0':np.nan,-8:np.nan,'-8':np.nan,-8.0:np.nan,'-8.0':np.nan})
result

,VMONTH,AGE,SEX,RACE,ETHNIC,RFV1,DIAG1,DIAG2,DIAG3,MED1,MED2,MED3,PATWT,REGION,YEAR,AGEDAYS,AGER,VDAYR,PREGNANT,PAYTYPE,MAJOR,TEMPF,BPSYS,BPDIAS,GLUCOSE,GESTWK,HTIN,WTLB,BMI,BONEDENS,ETHIM,RACEIM,DIAG4,DIAG5,SUBSTED,HTWTFL,received
0,10,6,1,1,1,14400,49390,159900,900000,60735,24355,33843,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,10,67,1,1,2,19201,72650,204430,115410,10126,05789,17165,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,10,47,1,1,2,41150,V6759,140190,127800,05789,19675,30553,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,10,69,2,1,2,31000,18890,204589,900000,60735,17865,34495,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,10,42,2,1,2,10552,84890,900000,900000,19675,05810,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
5,10,46,1,1,2,11100,31100,172100,130510,01530,17365,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
6,10,4,1,1,2,13551,47390,146590,900000,01630,29705,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
7,10,2,2,1,2,13551,38290,146590,900000,01630,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
8,10,58,1,1,2,22500,25000,900000,900000,15680,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
9,10,60,1,1,2,19401,72610,117490,204589,19675,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
10,10,42,1,1,2,31000,27800,900000,900000,31015,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
11,10,53,2,1,2,31000,72871,169290,900000,31015,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
12,10,28,2,1,2,18750,78560,900000,900000,90000,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
13,10,28,1,1,2,19006,20280,900000,900000,90000,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
14,2,81,2,1,2,15950,00880,149120,178030,93093,24890,31120,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
15,2,52,1,1,2,14400,49000,171400,900000,10905,24890,32845,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
16,2,72,1,1,2,15350,17490,153390,156400,17115,25674,21225,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
17,2,68,1,1,2,19700,71400,124490,127240,06935,19242,91011,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
18,2,86,2,1,2,12250,42731,141490,171590,17115,05789,16095,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
19,2,66,1,1,2,16600,59900,127200,140190,18130,05789,17883,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
20,2,70,1,1,2,25100,40190,127200,142410,40955,33858,19242,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
21,2,70,1,1,2,10150,31100,155330,127240,93181,30495,31740,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
22,2,51,1,1,2,14400,49000,201250,900000,10905,07930,32845,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
23,2,11,2,1,2,14400,49000,900000,900000,32840,01630,90000,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
24,2,21,2,1,2,10551,84830,900000,900000,15395,09900,90000,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
25,2,41,1,1,2,14000,38101,900000,900000,01630,11395,90000,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
26,2,55,2,1,2,61000,25001,900000,900000,17304,15680,90000,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
27,2,46,1,1,2,12600,78510,133382,900000,14000,30730,90000,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
28,2,8,1,1,2,14400,49000,900000,900000,01630,32840,90000,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
29,2,55,1,1,2,10050,49000,900000,900000,11665,32840,90000,88174,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13135,1,78,2,1,2,16150,NaN,NaN,1539,17370,61245,NaN,33316.84584,NaN,2016,NaN,6,4,NaN,2,5,955,100,60,0,NaN,71,126,17.57,0,2,NaN,2469,NaN,0,0,0
13136,1,55,2,1,2,26600,NaN,29632,4779,25674,NaN,NaN,33316.84584,NaN,2016,NaN,4,4,NaN,2,4,980,124,82,0,NaN,72,178,24.14,0,2,NaN,NaN,4550,0,0,0
13137,1,55,1,1,2,21000,NaN,1539,NaN,93396,NaN,NaN,33316.84584,NaN,2016,NaN,4,4,2,3,5,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,0
13138,1,58,2,1,2,42000,5531,55321,27800,91062,06985,89020,33316.84584,NaN,2016,NaN,4,6,NaN,3,4,985,156,94,0,NaN,71,263,36.68,0,2,NaN,NaN,NaN,0,0,0
13139,1,75,2,1,1,26600,5531,NaN,NaN,NaN,NaN,NaN,33316.84584,NaN,2016,NaN,6,6,NaN,3,5,981,102,60,0,NaN,64,154,26.43,0,1,NaN,NaN,NaN,0,0,0
13140,1,81,2,1,2,26600,NaN,NaN,49120,01030,02805,91063,33316.84584,NaN,2016,NaN,6,6,NaN,2,5,963,104,60,0,NaN,67,158,24.74,0,2,NaN,4439,5859,0,0,0
13141,1,66,2,NaN,2,19056,7062,NaN,27800,01030,91063,14930,33316.84584,NaN,2016,NaN,5,6,NaN,2,5,990,156,92,0,NaN,69,218,32.19,0,2,NaN,NaN,NaN,0,0,0
13142,1,59,1,1,2,46050,5759,NaN,NaN,NaN,NaN,NaN,33316.84584,NaN,2016,NaN,4,6,2,3,4,980,116,80,0,NaN,65,156,25.96,0,2,NaN,NaN,NaN,0,0,0
13143,1,84,1,1,2,13050,NaN,NaN,NaN,91063,24890,NaN,33316.84584,NaN,2016,NaN,6,6,NaN,2,4,969,130,60,0,NaN,66,118,19.04,0,2,NaN,73300,NaN,0,0,0
13144,1,36,2,NaN,2,46050,NaN,NaN,27800,97020,92164,95050,33316.84584,NaN,2016,NaN,3,6,NaN,1,4,986,130,84,0,NaN,71,263,36.68,0,2,NaN,NaN,NaN,0,0,0
13145,1,27,1,1,1,16100,NaN,NaN,NaN,32930,NaN,NaN,33316.84584,NaN,2016,NaN,3,6,2,1,5,958,118,78,0,NaN,61,159,30.04,0,1,NaN,NaN,NaN,0,0,1
13146,1,70,2,1,2,10600,NaN,NaN,29620,91063,06645,92164,33316.84584,NaN,2016,NaN,5,6,NaN,2,5,993,124,82,0,NaN,68,165,25.09,0,2,NaN,NaN,NaN,0,0,0
13147,1,55,1,1,1,42000,NaN,NaN,NaN,32930,NaN,NaN,33316.84584,NaN,2016,NaN,4,6,2,3,4,973,138,88,0,NaN,63,182,32.24,0,1,NaN,NaN,NaN,0,0,1
13148,1,71,2,NaN,2,25450,4556,53081,NaN,17485,01034,03229,33316.84584,NaN,2016,NaN,5,6,NaN,2,3,984,126,82,0,NaN,69,220,32.48,0,2,NaN,29620,NaN,0,0,0
13149,1,68,1,1,2,48000,NaN,NaN,NaN,26255,98036,92141,76524.39558,NaN,2016,NaN,5,4,NaN,2,2,970,154,71,0,NaN,69,NaN,NaN,0,2,NaN,78702,2859,0,0,1
13150,1,70,1,1,2,48000,NaN,NaN,NaN,04423,00274,92160,76524.39558,NaN,2016,NaN,5,4,NaN,2,2,969,144,79,0,NaN,65,184,30.62,0,2,NaN,NaN,NaN,0,0,0
13151,1,80,1,1,2,48000,7944,NaN,NaN,07551,02875,10355,76524.39558,NaN,2016,NaN,6,4,NaN,2,2,966,140,82,0,NaN,63,143,25.33,0,2,NaN,7049,NaN,0,0,0
13152,1,47,1,1,2,10150,NaN,NaN,NaN,99118,17370,61605,76524.39558,NaN,2016,NaN,4,4,2,1,2,982,119,69,0,NaN,64,177,30.38,0,2,NaN,NaN,NaN,0,0,0
13153,1,77,2,1,2,48000,NaN,NaN,NaN,12283,91096,93187,76524.39558,NaN,2016,NaN,6,4,NaN,2,2,972,115,56,0,NaN,68,172,26.15,0,2,NaN,NaN,NaN,0,0,0
13154,1,63,2,1,NaN,45210,NaN,NaN,NaN,02333,28495,32905,76524.39558,NaN,2016,NaN,4,4,NaN,2,2,954,142,73,0,NaN,76,255,31.04,0,2,NaN,NaN,NaN,0,0,0
13155,1,80,1,1,2,15350,NaN,V103,NaN,01640,92105,14985,76524.39558,NaN,2016,NaN,6,4,NaN,2,2,969,135,83,0,NaN,63,167,29.58,0,2,NaN,28803,NaN,0,0,0
13156,1,66,1,1,2,10150,NaN,NaN,NaN,04423,32735,34495,76524.39558,NaN,2016,NaN,5,4,NaN,2,2,969,125,67,0,NaN,68,172,26.15,0,2,NaN,NaN,NaN,0,0,0
13157,1,41,1,1,2,19351,NaN,NaN,NaN,04622,95181,02351,76524.39558,NaN,2016,NaN,3,6,2,5,2,978,143,80,0,NaN,65,251,41.76,0,2,NaN,NaN,NaN,0,0,0
13158,1,69,2,1,2,48000,1539,NaN,NaN,14985,92164,60790,76524.39558,NaN,2016,NaN,5,6,NaN,2,2,951,112,75,0,NaN,74,194,24.91,0,2,NaN,1977,NaN,0,0,0
13159,1,58,1,5,1,48000,NaN,72982,NaN,02156,93181,91096,76524.39558,NaN,2016,NaN,4,6,2,5,2,985,138,78,0,NaN,61,176,33.25,0,1,NaN,NaN,NaN,0,0,0
13160,1,69,2,1,2,48000,NaN,NaN,NaN,08770,14083,96044,76524.39558,NaN,2016,NaN,5,6,NaN,2,2,964,131,64,0,NaN,69,155,22.89,0,2,NaN,NaN,NaN,0,0,0
13161,1,66,2,1,2,10601,NaN,NaN,NaN,09600,92105,07470,76524.39558,NaN,2016,NaN,5,6,NaN,2,2,976,135,76,0,NaN,70,153,21.95,0,2,NaN,NaN,NaN,0,0,1
13162,1,80,1,2,2,46050,1543,25000,NaN,93181,17485,12081,76524.39558,NaN,2016,NaN,6,6,NaN,2,3,979,110,64,0,NaN,66,147,23.72,0,2,NaN,NaN,NaN,0,0,0
13163,1,76,1,1,1,12400,1830,NaN,3079,02900,08585,19242,76524.39558,NaN,2016,NaN,6,6,NaN,2,2,982,151,79,0,NaN,62,145,26.52,0,1,NaN,NaN,NaN,0,0,0
13164,1,73,2,1,2,48000,NaN,NaN,NaN,NaN,NaN,NaN,76524.39558,NaN,2016,NaN,5,6,NaN,2,2,967,120,70,0,NaN,61,131,24.75,0,2,NaN,NaN,NaN,0,0,0

In [16]:
result[result.received == 1]

,VMONTH,AGE,SEX,RACE,ETHNIC,RFV1,DIAG1,DIAG2,DIAG3,MED1,MED2,MED3,PATWT,REGION,YEAR,AGEDAYS,AGER,VDAYR,PREGNANT,PAYTYPE,MAJOR,TEMPF,BPSYS,BPDIAS,GLUCOSE,GESTWK,HTIN,WTLB,BMI,BONEDENS,ETHIM,RACEIM,DIAG4,DIAG5,SUBSTED,HTWTFL,received
88,8,21,2,2,2,19401,84890,900000,900000,32930,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
89,8,41,1,4,2,10554,35010,900000,900000,32930,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
153,3,49,1,1,2,26000,47390,153010,900000,08470,41780,90000,65651,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
198,8,18,1,1,2,32050,V2220,164663,900000,24975,32905,32920,26956,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
214,8,47,1,1,2,19401,72340,900000,900000,32920,90000,90000,26956,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
246,4,37,2,1,2,11000,30490,900000,900000,18985,90000,90000,27599,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
327,2,73,1,1,2,11000,40190,130000,173300,26045,30782,08470,77781,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
358,7,68,1,1,2,19201,45190,900000,900000,50035,19242,08470,58381,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
359,7,65,1,1,2,19251,71590,140190,199520,05347,08470,32905,58381,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
378,7,71,2,1,2,12201,71941,105319,900000,61100,34110,11152,89911,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
418,11,50,2,1,2,19051,72450,900000,900000,15395,01530,32930,25448,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
709,11,29,1,2,2,14400,49390,900000,900000,27195,34110,90000,106010,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
770,10,67,1,1,2,15451,56410,156800,157160,18930,17375,92180,100331,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
788,10,30,1,1,2,55050,92000,900000,900000,92180,90000,90000,100331,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
826,11,40,1,1,2,10551,48600,180700,900000,32920,02158,93194,98839,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
877,4,40,2,1,2,19101,72420,147390,900000,34110,16475,19675,93952,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
887,4,41,2,1,2,19051,72450,201350,900000,32920,12635,19675,93952,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
936,4,24,2,1,1,19600,92330,900000,900000,12565,16475,90000,56775,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
968,4,51,2,1,2,55750,84600,900000,900000,20210,26785,08470,90950,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
999,10,52,1,1,2,12100,34690,900000,900000,32920,90000,90000,47703,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1083,9,45,1,2,2,19652,72690,900000,900000,15395,08475,90000,90950,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1135,6,78,1,1,2,31000,42800,141490,900000,32920,05145,27785,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1165,6,45,2,1,2,19051,72900,900000,900000,92180,90000,90000,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1172,8,25,2,2,2,41150,34690,900000,900000,32920,40520,08836,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1175,8,40,2,1,2,13600,38090,138010,900000,05993,34740,34110,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1177,8,11,2,1,2,15350,73730,900000,900000,18558,92180,61160,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1178,9,42,2,2,2,41150,V6810,900000,900000,35023,08475,90000,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1181,9,61,1,1,2,10502,78659,178620,900000,31927,34110,90000,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1191,10,54,1,1,2,31000,V6790,900000,900000,35023,08475,90000,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1196,10,25,1,1,2,12100,34690,900000,900000,32920,90000,90000,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12393,12,57,2,1,NaN,15104,NaN,NaN,NaN,08354,17888,04051,37788.51689,NaN,2016,NaN,4,4,NaN,1,3,NaN,125,86,0,NaN,69,189,27.91,0,2,NaN,NaN,NaN,0,0,1
12508,8,69,1,1,2,48000,NaN,NaN,NaN,89039,05051,17370,34890.93178,NaN,2016,NaN,5,2,NaN,2,6,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12536,8,38,2,2,2,35000,NaN,NaN,NaN,14955,33555,NaN,34890.93178,NaN,2016,NaN,3,6,NaN,1,5,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12562,9,68,1,1,2,19251,NaN,NaN,NaN,05187,14955,17370,55104.23915,NaN,2016,NaN,5,2,NaN,2,1,NaN,NaN,NaN,0,NaN,67,150,23.49,0,2,NaN,NaN,NaN,0,0,1
12569,9,78,2,1,1,48000,NaN,NaN,NaN,14955,05097,01030,55104.23915,NaN,2016,NaN,6,2,NaN,NaN,1,NaN,NaN,NaN,0,NaN,70,180,25.82,0,1,NaN,NaN,NaN,0,0,1
12734,1,38,2,NaN,NaN,28000,NaN,NaN,NaN,19699,19675,94099,67023.29034,NaN,2016,NaN,3,3,NaN,1,3,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12735,1,47,1,1,2,48000,NaN,NaN,NaN,14965,98036,NaN,67023.29034,NaN,2016,NaN,4,3,2,1,5,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12744,1,46,1,1,NaN,45210,NaN,NaN,NaN,19675,98036,23755,67023.29034,NaN,2016,NaN,4,5,2,1,4,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12759,2,46,2,1,2,10601,7242,72280,NaN,98036,93355,97073,62919.82358,NaN,2016,NaN,4,6,NaN,2,2,NaN,NaN,NaN,0,NaN,71,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12761,2,27,2,1,2,19101,NaN,NaN,NaN,18640,15395,98036,62919.82358,NaN,2016,NaN,3,4,NaN,4,3,NaN,NaN,NaN,0,NaN,76,310,37.73,0,2,NaN,NaN,NaN,0,0,1
12766,2,42,1,2,2,19001,NaN,NaN,NaN,95133,19218,98036,62919.82358,NaN,2016,NaN,3,4,2,3,1,NaN,NaN,NaN,0,NaN,66,190,30.66,0,2,NaN,NaN,NaN,0,0,1
12769,2,37,2,1,2,19101,7242,30009,NaN,98036,12635,35023,62919.82358,NaN,2016,NaN,3,3,NaN,1,2,NaN,NaN,NaN,0,NaN,70,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12770,2,48,1,2,2,10601,NaN,NaN,NaN,98036,96041,99133,62919.82358,NaN,2016,NaN,4,3,2,1,1,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12816,12,37,1,1,2,46050,NaN,3384,NaN,14955,92164,03381,25464.61889,NaN,2016,NaN,3,2,2,3,6,971,146,91,0,NaN,69,142,20.97,0,2,NaN,NaN,NaN,0,0,1
12949,6,78,2,1,NaN,19101,7242,NaN,NaN,12635,32920,94125,93886.72186,NaN,2016,NaN,6,3,NaN,2,1,970,114,78,0,NaN,70,220,31.56,0,2,NaN,NaN,NaN,0,0,1
13096,8,65,2,5,2,41150,NaN,7245,25000,14955,93305,98115,114091.81487,NaN,2016,NaN,5,4,NaN,2,2,983,148,70,0,NaN,70,170,24.39,0,2,NaN,NaN,NaN,0,0,1
13104,8,33,2,NaN,1,10601,NaN,7245,7231,96041,34110,98115,114091.81487,NaN,2016,NaN,3,5,NaN,3,1,992,120,70,0,NaN,72,238,32.28,0,1,NaN,NaN,NaN,0,0,1
13106,8,59,1,5,2,41150,7242,NaN,78050,60735,96125,34110,114091.81487,NaN,2016,NaN,4,5,2,3,2,983,118,76,0,NaN,66,149,24.05,0,2,NaN,NaN,NaN,0,0,1
13109,8,63,2,5,2,41150,NaN,NaN,78050,34110,97174,97157,114091.81487,NaN,2016,NaN,4,4,NaN,1,1,968,144,82,1,NaN,67,159,24.9,0,2,NaN,NaN,29620,1,0,1
13115,1,59,1,1,1,25450,4556,NaN,NaN,91063,14955,17888,33316.84584,NaN,2016,NaN,4,2,2,3,3,972,124,80,0,NaN,61,175,33.06,0,1,NaN,30001,29620,0,0,1
13116,1,87,2,1,2,26600,NaN,NaN,NaN,96028,02805,03381,33316.84584,NaN,2016,NaN,6,2,NaN,2,5,972,142,82,0,NaN,69,150,22.15,0,2,NaN,NaN,NaN,0,0,1
13117,1,63,2,1,NaN,26600,55321,NaN,NaN,99114,92124,12635,33316.84584,NaN,2016,NaN,4,2,NaN,1,5,988,126,82,0,NaN,66,262,42.28,0,2,NaN,NaN,NaN,0,0,1
13121,1,74,2,1,2,42000,NaN,NaN,NaN,32930,01030,13118,33316.84584,NaN,2016,NaN,5,3,NaN,2,1,989,130,82,0,NaN,77,241,-5,0,2,NaN,NaN,NaN,0,1,1
13122,1,60,2,1,2,42000,NaN,NaN,2113,32930,92164,NaN,33316.84584,NaN,2016,NaN,4,3,NaN,3,4,974,142,80,0,NaN,70,217,31.13,0,2,NaN,NaN,4550,0,0,1
13123,1,52,2,1,2,25450,4553,25000,NaN,32930,99090,96027,33316.84584,NaN,2016,NaN,4,3,NaN,1,4,984,150,92,0,NaN,64,166,28.49,0,2,NaN,NaN,NaN,0,0,1
13124,1,84,2,1,1,26600,NaN,NaN,NaN,32930,09809,07170,33316.84584,NaN,2016,NaN,6,4,NaN,2,4,987,134,82,0,NaN,70,192,27.55,0,1,NaN,2449,5853,0,0,1
13145,1,27,1,1,1,16100,NaN,NaN,NaN,32930,NaN,NaN,33316.84584,NaN,2016,NaN,3,6,2,1,5,958,118,78,0,NaN,61,159,30.04,0,1,NaN,NaN,NaN,0,0,1
13147,1,55,1,1,1,42000,NaN,NaN,NaN,32930,NaN,NaN,33316.84584,NaN,2016,NaN,4,6,2,3,4,973,138,88,0,NaN,63,182,32.24,0,1,NaN,NaN,NaN,0,0,1
13149,1,68,1,1,2,48000,NaN,NaN,NaN,26255,98036,92141,76524.39558,NaN,2016,NaN,5,4,NaN,2,2,970,154,71,0,NaN,69,NaN,NaN,0,2,NaN,78702,2859,0,0,1
13161,1,66,2,1,2,10601,NaN,NaN,NaN,09600,92105,07470,76524.39558,NaN,2016,NaN,5,6,NaN,2,2,976,135,76,0,NaN,70,153,21.95,0,2,NaN,NaN,NaN,0,0,1

In [17]:
# Store the table as we currently have it, to prevent needing to remake it over and over
result.to_csv('data_files/result_original.csv')

In [15]:
# read in that pre-made table
result = pd.read_csv('data_files/result_original.csv')

In [16]:
result[result.received == 1]

,Unnamed: 0,VMONTH,AGE,SEX,RACE,ETHNIC,RFV1,DIAG1,MED1,MED2,PATWT,REGION,YEAR,AGEDAYS,AGER,VDAYR,PREGNANT,PAYTYPE,MAJOR,TEMPF,BPSYS,BPDIAS,GLUCOSE,GESTWK,HTIN,WTLB,BMI,BONEDENS,ETHIM,RACEIM,SUBSTED,HTWTFL,received
88,88,8,21,2,2.0,2.0,19401.0,84890,32930.0,90000.0,95686.00000,1.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
89,89,8,41,1,4.0,2.0,10554.0,35010,32930.0,90000.0,95686.00000,1.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
153,153,3,49,1,1.0,2.0,26000.0,47390,8470.0,41780.0,65651.00000,1.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
214,214,8,47,1,1.0,2.0,19401.0,72340,32920.0,90000.0,26956.00000,1.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
246,246,4,37,2,1.0,2.0,11000.0,30490,18985.0,90000.0,27599.00000,1.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
359,359,7,65,1,1.0,2.0,19251.0,71590,5347.0,8470.0,58381.00000,1.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
378,378,7,71,2,1.0,2.0,12201.0,71941,61100.0,34110.0,89911.00000,2.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
709,709,11,29,1,2.0,2.0,14400.0,49390,27195.0,34110.0,106010.00000,2.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
788,788,10,30,1,1.0,2.0,55050.0,92000,92180.0,90000.0,100331.00000,2.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
826,826,11,40,1,1.0,2.0,10551.0,48600,32920.0,2158.0,98839.00000,2.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
877,877,4,40,2,1.0,2.0,19101.0,72420,34110.0,16475.0,93952.00000,2.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
887,887,4,41,2,1.0,2.0,19051.0,72450,32920.0,12635.0,93952.00000,2.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
936,936,4,24,2,1.0,1.0,19600.0,92330,12565.0,16475.0,56775.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
999,999,10,52,1,1.0,2.0,12100.0,34690,32920.0,90000.0,47703.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1083,1083,9,45,1,2.0,2.0,19652.0,72690,15395.0,8475.0,90950.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1135,1135,6,78,1,1.0,2.0,31000.0,42800,32920.0,5145.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1165,1165,6,45,2,1.0,2.0,19051.0,72900,92180.0,90000.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1172,1172,8,25,2,2.0,2.0,41150.0,34690,32920.0,40520.0,52554.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1177,1177,8,11,2,1.0,2.0,15350.0,73730,18558.0,92180.0,52554.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1178,1178,9,42,2,2.0,2.0,41150.0,V6810,35023.0,8475.0,52554.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1181,1181,9,61,1,1.0,2.0,10502.0,78659,31927.0,34110.0,52554.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1191,1191,10,54,1,1.0,2.0,31000.0,V6790,35023.0,8475.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1196,1196,10,25,1,1.0,2.0,12100.0,34690,32920.0,90000.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1197,1197,10,7,1,1.0,2.0,14400.0,46610,34110.0,90000.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1231,1231,2,10,1,1.0,2.0,10100.0,38290,5955.0,92180.0,97633.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1258,1258,12,37,2,1.0,2.0,10553.0,72709,12193.0,8470.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1282,1282,8,35,1,1.0,2.0,90000.0,68270,93089.0,16475.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1287,1287,8,31,2,1.0,2.0,19351.0,84500,8470.0,90000.0,101334.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1315,1315,1,78,1,2.0,2.0,19151.0,72190,8470.0,27103.0,95537.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1337,1337,1,45,2,1.0,2.0,25100.0,34000,32920.0,90000.0,95537.00000,3.0,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764382,12147,9,47,1,1.0,2.0,19051.0,7245,1002.0,92180.0,67938.80265,NaN,2016,NaN,4.0,4.0,2.0,3.0,1.0,NaN,150.0,85.0,0.0,NaN,63.0,220.0,38.97,0.0,2.0,NaN,0.0,0.0,1
764556,12321,5,60,2,1.0,2.0,41150.0,71536,96041.0,98036.0,38222.47591,NaN,2016,NaN,4.0,4.0,NaN,1.0,2.0,NaN,142.0,76.0,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
764619,12384,12,18,1,1.0,NaN,42050.0,NaN,89039.0,NaN,37788.51689,NaN,2016,NaN,2.0,3.0,2.0,7.0,5.0,NaN,125.0,86.0,0.0,NaN,67.0,160.0,25.06,0.0,2.0,NaN,0.0,0.0,1
764628,12393,12,57,2,1.0,NaN,15104.0,NaN,8354.0,17888.0,37788.51689,NaN,2016,NaN,4.0,4.0,NaN,1.0,3.0,NaN,125.0,86.0,0.0,NaN,69.0,189.0,27.91,0.0,2.0,NaN,0.0,0.0,1
764743,12508,8,69,1,1.0,2.0,48000.0,NaN,89039.0,5051.0,34890.93178,NaN,2016,NaN,5.0,2.0,NaN,2.0,6.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
764771,12536,8,38,2,2.0,2.0,35000.0,NaN,14955.0,33555.0,34890.93178,NaN,2016,NaN,3.0,6.0,NaN,1.0,5.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
764797,12562,9,68,1,1.0,2.0,19251.0,NaN,5187.0,14955.0,55104.23915,NaN,2016,NaN,5.0,2.0,NaN,2.0,1.0,NaN,NaN,NaN,0.0,NaN,67.0,150.0,23.49,0.0,2.0,NaN,0.0,0.0,1
764804,12569,9,78,2,1.0,1.0,48000.0,NaN,14955.0,5097.0,55104.23915,NaN,2016,NaN,6.0,2.0,NaN,NaN,1.0,NaN,NaN,NaN,0.0,NaN,70.0,180.0,25.82,0.0,1.0,NaN,0.0,0.0,1
764969,12734,1,38,2,NaN,NaN,28000.0,NaN,19699.0,19675.0,67023.29034,NaN,2016,NaN,3.0,3.0,NaN,1.0,3.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
764970,12735,1,47,1,1.0,2.0,48000.0,NaN,14965.0,98036.0,67023.29034,NaN,2016,NaN,4.0,3.0,2.0,1.0,5.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
764979,12744,1,46,1,1.0,NaN,45210.0,NaN,19675.0,98036.0,67023.29034,NaN,2016,NaN,4.0,5.0,2.0,1.0,4.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
764994,12759,2,46,2,1.0,2.0,10601.0,7242,98036.0,93355.0,62919.82358,NaN,2016,NaN,4.0,6.0,NaN,2.0,2.0,NaN,NaN,NaN,0.0,NaN,71.0,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
765004,12769,2,37,2,1.0,2.0,19101.0,7242,98036.0,12635.0,62919.82358,NaN,2016,NaN,3.0,3.0,NaN,1.0,2.0,NaN,NaN,NaN,0.0,NaN,70.0,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
765005,12770,2,48,1,2.0,2.0,10601.0,NaN,98036.0,96041.0,62919.82358,NaN,2016,NaN,4.0,3.0,2.0,1.0,1.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
765051,12816,12,37,1,1.0,2.0,46050.0,NaN,14955.0,92164.0,25464.61889,NaN,2016,NaN,3.0,2.0,2.0,3.0,6.0,971.0,146.0,91.0,0.0,NaN,69.0,142.0,20.97,0.0,2.0,NaN,0.0,0.0,1
765184,12949,6,78,2,1.0,NaN,19101.0,7242,12635.0,32920.0,93886.72186,NaN,2016,NaN,6.0,3.0,NaN,2.0,1.0,970.0,114.0,78.0,0.0,NaN,70.0,220.0,31.56,0.0,2.0,NaN,0.0,0.0,1
765331,13096,8,65,2,5.0,2.0,41150.0,NaN,14955.0,93305.0,114091.81487,NaN,2016,NaN,5.0,4.0,NaN,2.0,2.0,983.0,148.0,70.0,0.0,NaN,70.0,170.0,24.39,0.0,2.0,NaN,0.0,0.0,1
765339,13104,8,33,2,NaN,1.0,10601.0,NaN,96041.0,34110.0,114091.81487,NaN,2016,NaN,3.0,5.0,NaN,3.0,1.0,992.0,120.0,70.0,0.0,NaN,72.0,238.0,32.28,0.0,1.0,NaN,0.0,0.0,1
765344,13109,8,63,2,5.0,2.0,41150.0,NaN,34110.0,97174.0,114091.81487,NaN,2016,NaN,4.0,4.0,NaN,1.0,1.0,968.0,144.0,82.0,1.0,NaN,67.0,159.0,24.90,0.0,2.0,NaN,1.0,0.0,1
765350,13115,1,59,1,1.0,1.0,25450.0,4556,91063.0,14955.0,33316.84584,NaN,2016,NaN,4.0,2.0,2.0,3.0,3.0,972.0,124.0,80.0,0.0,NaN,61.0,175.0,33.06,0.0,1.0,NaN,0.0,0.0,1
765351,13116,1,87,2,1.0,2.0,26600.0,NaN,96028.0,2805.0,33316.84584,NaN,2016,NaN,6.0,2.0,NaN,2.0,5.0,972.0,142.0,82.0,0.0,NaN,69.0,150.0,22.15,0.0,2.0,NaN,0.0,0.0,1
765352,13117,1,63,2,1.0,NaN,26600.0,55321,99114.0,92124.0,33316.84584,NaN,2016,NaN,4.0,2.0,NaN,1.0,5.0,988.0,126.0,82.0,0.0,NaN,66.0,262.0,42.28,0.0,2.0,NaN,0.0,0.0,1
765356,13121,1,74,2,1.0,2.0,42000.0,NaN,32930.0,1030.0,33316.84584,NaN,2016,NaN,5.0,3.0,NaN,2.0,1.0,989.0,130.0,82.0,0.0,NaN,77.0,241.0,-5.00,0.0,2.0,NaN,0.0,1.0,1
765357,13122,1,60,2,1.0,2.0,42000.0,NaN,32930.0,92164.0,33316.84584,NaN,2016,NaN,4.0,3.0,NaN,3.0,4.0,974.0,142.0,80.0,0.0,NaN,70.0,217.0,31.13,0.0,2.0,NaN,0.0,0.0,1
765358,13123,1,52,2,1.0,2.0,25450.0,4553,32930.0,99090.0,33316.84584,NaN,2016,NaN,4.0,3.0,NaN,1.0,4.0,984.0,150.0,92.0,0.0,NaN,64.0,166.0,28.49,0.0,2.0,NaN,0.0,0.0,1
765359,13124,1,84,2,1.0,1.0,26600.0,NaN,32930.0,9809.0,33316.84584,NaN,2016,NaN,6.0,4.0,NaN,2.0,4.0,987.0,134.0,82.0,0.0,NaN,70.0,192.0,27.55,0.0,1.0,NaN,0.0,0.0,1
765380,13145,1,27,1,1.0,1.0,16100.0,NaN,32930.0,NaN,33316.84584,NaN,2016,NaN,3.0,6.0,2.0,1.0,5.0,958.0,118.0,78.0,0.0,NaN,61.0,159.0,30.04,0.0,1.0,NaN,0.0,0.0,1
765382,13147,1,55,1,1.0,1.0,42000.0,NaN,32930.0,NaN,33316.84584,NaN,2016,NaN,4.0,6.0,2.0,3.0,4.0,973.0,138.0,88.0,0.0,NaN,63.0,182.0,32.24,0.0,1.0,NaN,0.0,0.0,1
765384,13149,1,68,1,1.0,2.0,48000.0,NaN,26255.0,98036.0,76524.39558,NaN,2016,NaN,5.0,4.0,NaN,2.0,2.0,970.0,154.0,71.0,0.0,NaN,69.0,NaN,NaN,0.0,2.0,NaN,0.0,0.0,1
765396,13161,1,66,2,1.0,2.0,10601.0,NaN,9600.0,92105.0,76524.39558,NaN,2016,NaN,5.0,6.0,NaN,2.0,2.0,976.0,135.0,76.0,0.0,NaN,70.0,153.0,21.95,0.0,2.0,NaN,0.0,0.0,1

In [18]:
opiates = result[result.received == 1]
opiates

,VMONTH,AGE,SEX,RACE,ETHNIC,RFV1,DIAG1,DIAG2,DIAG3,MED1,MED2,MED3,PATWT,REGION,YEAR,AGEDAYS,AGER,VDAYR,PREGNANT,PAYTYPE,MAJOR,TEMPF,BPSYS,BPDIAS,GLUCOSE,GESTWK,HTIN,WTLB,BMI,BONEDENS,ETHIM,RACEIM,DIAG4,DIAG5,SUBSTED,HTWTFL,received
88,8,21,2,2,2,19401,84890,900000,900000,32930,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
89,8,41,1,4,2,10554,35010,900000,900000,32930,90000,90000,95686,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
153,3,49,1,1,2,26000,47390,153010,900000,08470,41780,90000,65651,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
198,8,18,1,1,2,32050,V2220,164663,900000,24975,32905,32920,26956,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
214,8,47,1,1,2,19401,72340,900000,900000,32920,90000,90000,26956,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
246,4,37,2,1,2,11000,30490,900000,900000,18985,90000,90000,27599,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
327,2,73,1,1,2,11000,40190,130000,173300,26045,30782,08470,77781,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
358,7,68,1,1,2,19201,45190,900000,900000,50035,19242,08470,58381,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
359,7,65,1,1,2,19251,71590,140190,199520,05347,08470,32905,58381,1,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
378,7,71,2,1,2,12201,71941,105319,900000,61100,34110,11152,89911,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
418,11,50,2,1,2,19051,72450,900000,900000,15395,01530,32930,25448,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
709,11,29,1,2,2,14400,49390,900000,900000,27195,34110,90000,106010,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
770,10,67,1,1,2,15451,56410,156800,157160,18930,17375,92180,100331,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
788,10,30,1,1,2,55050,92000,900000,900000,92180,90000,90000,100331,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
826,11,40,1,1,2,10551,48600,180700,900000,32920,02158,93194,98839,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
877,4,40,2,1,2,19101,72420,147390,900000,34110,16475,19675,93952,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
887,4,41,2,1,2,19051,72450,201350,900000,32920,12635,19675,93952,2,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
936,4,24,2,1,1,19600,92330,900000,900000,12565,16475,90000,56775,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
968,4,51,2,1,2,55750,84600,900000,900000,20210,26785,08470,90950,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
999,10,52,1,1,2,12100,34690,900000,900000,32920,90000,90000,47703,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1083,9,45,1,2,2,19652,72690,900000,900000,15395,08475,90000,90950,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1135,6,78,1,1,2,31000,42800,141490,900000,32920,05145,27785,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1165,6,45,2,1,2,19051,72900,900000,900000,92180,90000,90000,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1172,8,25,2,2,2,41150,34690,900000,900000,32920,40520,08836,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1175,8,40,2,1,2,13600,38090,138010,900000,05993,34740,34110,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1177,8,11,2,1,2,15350,73730,900000,900000,18558,92180,61160,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1178,9,42,2,2,2,41150,V6810,900000,900000,35023,08475,90000,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1181,9,61,1,1,2,10502,78659,178620,900000,31927,34110,90000,52554,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1191,10,54,1,1,2,31000,V6790,900000,900000,35023,08475,90000,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1196,10,25,1,1,2,12100,34690,900000,900000,32920,90000,90000,101334,3,1993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12393,12,57,2,1,NaN,15104,NaN,NaN,NaN,08354,17888,04051,37788.51689,NaN,2016,NaN,4,4,NaN,1,3,NaN,125,86,0,NaN,69,189,27.91,0,2,NaN,NaN,NaN,0,0,1
12508,8,69,1,1,2,48000,NaN,NaN,NaN,89039,05051,17370,34890.93178,NaN,2016,NaN,5,2,NaN,2,6,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12536,8,38,2,2,2,35000,NaN,NaN,NaN,14955,33555,NaN,34890.93178,NaN,2016,NaN,3,6,NaN,1,5,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12562,9,68,1,1,2,19251,NaN,NaN,NaN,05187,14955,17370,55104.23915,NaN,2016,NaN,5,2,NaN,2,1,NaN,NaN,NaN,0,NaN,67,150,23.49,0,2,NaN,NaN,NaN,0,0,1
12569,9,78,2,1,1,48000,NaN,NaN,NaN,14955,05097,01030,55104.23915,NaN,2016,NaN,6,2,NaN,NaN,1,NaN,NaN,NaN,0,NaN,70,180,25.82,0,1,NaN,NaN,NaN,0,0,1
12734,1,38,2,NaN,NaN,28000,NaN,NaN,NaN,19699,19675,94099,67023.29034,NaN,2016,NaN,3,3,NaN,1,3,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12735,1,47,1,1,2,48000,NaN,NaN,NaN,14965,98036,NaN,67023.29034,NaN,2016,NaN,4,3,2,1,5,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12744,1,46,1,1,NaN,45210,NaN,NaN,NaN,19675,98036,23755,67023.29034,NaN,2016,NaN,4,5,2,1,4,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12759,2,46,2,1,2,10601,7242,72280,NaN,98036,93355,97073,62919.82358,NaN,2016,NaN,4,6,NaN,2,2,NaN,NaN,NaN,0,NaN,71,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12761,2,27,2,1,2,19101,NaN,NaN,NaN,18640,15395,98036,62919.82358,NaN,2016,NaN,3,4,NaN,4,3,NaN,NaN,NaN,0,NaN,76,310,37.73,0,2,NaN,NaN,NaN,0,0,1
12766,2,42,1,2,2,19001,NaN,NaN,NaN,95133,19218,98036,62919.82358,NaN,2016,NaN,3,4,2,3,1,NaN,NaN,NaN,0,NaN,66,190,30.66,0,2,NaN,NaN,NaN,0,0,1
12769,2,37,2,1,2,19101,7242,30009,NaN,98036,12635,35023,62919.82358,NaN,2016,NaN,3,3,NaN,1,2,NaN,NaN,NaN,0,NaN,70,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12770,2,48,1,2,2,10601,NaN,NaN,NaN,98036,96041,99133,62919.82358,NaN,2016,NaN,4,3,2,1,1,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,0,2,NaN,NaN,NaN,0,0,1
12816,12,37,1,1,2,46050,NaN,3384,NaN,14955,92164,03381,25464.61889,NaN,2016,NaN,3,2,2,3,6,971,146,91,0,NaN,69,142,20.97,0,2,NaN,NaN,NaN,0,0,1
12949,6,78,2,1,NaN,19101,7242,NaN,NaN,12635,32920,94125,93886.72186,NaN,2016,NaN,6,3,NaN,2,1,970,114,78,0,NaN,70,220,31.56,0,2,NaN,NaN,NaN,0,0,1
13096,8,65,2,5,2,41150,NaN,7245,25000,14955,93305,98115,114091.81487,NaN,2016,NaN,5,4,NaN,2,2,983,148,70,0,NaN,70,170,24.39,0,2,NaN,NaN,NaN,0,0,1
13104,8,33,2,NaN,1,10601,NaN,7245,7231,96041,34110,98115,114091.81487,NaN,2016,NaN,3,5,NaN,3,1,992,120,70,0,NaN,72,238,32.28,0,1,NaN,NaN,NaN,0,0,1
13106,8,59,1,5,2,41150,7242,NaN,78050,60735,96125,34110,114091.81487,NaN,2016,NaN,4,5,2,3,2,983,118,76,0,NaN,66,149,24.05,0,2,NaN,NaN,NaN,0,0,1
13109,8,63,2,5,2,41150,NaN,NaN,78050,34110,97174,97157,114091.81487,NaN,2016,NaN,4,4,NaN,1,1,968,144,82,1,NaN,67,159,24.9,0,2,NaN,NaN,29620,1,0,1
13115,1,59,1,1,1,25450,4556,NaN,NaN,91063,14955,17888,33316.84584,NaN,2016,NaN,4,2,2,3,3,972,124,80,0,NaN,61,175,33.06,0,1,NaN,30001,29620,0,0,1
13116,1,87,2,1,2,26600,NaN,NaN,NaN,96028,02805,03381,33316.84584,NaN,2016,NaN,6,2,NaN,2,5,972,142,82,0,NaN,69,150,22.15,0,2,NaN,NaN,NaN,0,0,1
13117,1,63,2,1,NaN,26600,55321,NaN,NaN,99114,92124,12635,33316.84584,NaN,2016,NaN,4,2,NaN,1,5,988,126,82,0,NaN,66,262,42.28,0,2,NaN,NaN,NaN,0,0,1
13121,1,74,2,1,2,42000,NaN,NaN,NaN,32930,01030,13118,33316.84584,NaN,2016,NaN,5,3,NaN,2,1,989,130,82,0,NaN,77,241,-5,0,2,NaN,NaN,NaN,0,1,1
13122,1,60,2,1,2,42000,NaN,NaN,2113,32930,92164,NaN,33316.84584,NaN,2016,NaN,4,3,NaN,3,4,974,142,80,0,NaN,70,217,31.13,0,2,NaN,NaN,4550,0,0,1
13123,1,52,2,1,2,25450,4553,25000,NaN,32930,99090,96027,33316.84584,NaN,2016,NaN,4,3,NaN,1,4,984,150,92,0,NaN,64,166,28.49,0,2,NaN,NaN,NaN,0,0,1
13124,1,84,2,1,1,26600,NaN,NaN,NaN,32930,09809,07170,33316.84584,NaN,2016,NaN,6,4,NaN,2,4,987,134,82,0,NaN,70,192,27.55,0,1,NaN,2449,5853,0,0,1
13145,1,27,1,1,1,16100,NaN,NaN,NaN,32930,NaN,NaN,33316.84584,NaN,2016,NaN,3,6,2,1,5,958,118,78,0,NaN,61,159,30.04,0,1,NaN,NaN,NaN,0,0,1
13147,1,55,1,1,1,42000,NaN,NaN,NaN,32930,NaN,NaN,33316.84584,NaN,2016,NaN,4,6,2,3,4,973,138,88,0,NaN,63,182,32.24,0,1,NaN,NaN,NaN,0,0,1
13149,1,68,1,1,2,48000,NaN,NaN,NaN,26255,98036,92141,76524.39558,NaN,2016,NaN,5,4,NaN,2,2,970,154,71,0,NaN,69,NaN,NaN,0,2,NaN,78702,2859,0,0,1
13161,1,66,2,1,2,10601,NaN,NaN,NaN,09600,92105,07470,76524.39558,NaN,2016,NaN,5,6,NaN,2,2,976,135,76,0,NaN,70,153,21.95,0,2,NaN,NaN,NaN,0,0,1

In [19]:
# Store the df of patients who received opiates for later analysis
opiates.to_csv("data_files/opiate_receivers.csv")